name: Create Issue From File Example Command
on:
  repository_dispatch:
    types: [ciff-example-command]
  workflow_dispatch:
jobs:
  createIssueFromFile:
    runs-on: ubuntu-latest
    steps:
      # Get the target repository and branch
      - name: Get the target repository and branch
        id: vars
        run: |
          repository=${{ github.event.client_payload.slash_command.repository }}
          if [[ -z "$repository" ]]; then repository=${{ github.repository }}; fi
          echo ::set-output name=repository::$repository
          branch=${{ github.event.client_payload.slash_command.branch }}
          if [[ -z "$branch" ]]; then branch="main"; fi
          echo ::set-output name=branch::$branch

      # Checkout the branch to test
      - uses: actions/checkout@v2
        with:
          repository: ${{ steps.vars.outputs.repository }}
          ref: ${{ steps.vars.outputs.branch }}

      # Test create
      - name: Create Issue From File
        id: ciff
        uses: ./
        with:
          title: An example issue
          content-filepath: ./example-content/output.md
          labels: |
            report
            automated issue
          assignees: peter-evans

      # Test update
      - name: Update Issue From File
        uses: ./
        with:
          issue-number: ${{ steps.ciff.outputs.issue-number }}
          title: An UPDATED example issue
          content-filepath: ./example-content/update.md
          labels: |
            report
            automated issue
          assignees: peter-evans

